# Input video file
video_file: 'kirby.wmv'

# Constants used in pipeline
resize: 0.25
frame_parse: 1
mb_kern: 3
px_thresh: 50
min_obj_size: 100
velocity_window: 2
w_1: 1.0
w_2: 0.1
w_3: 0.3
sigma: 0.2
p: 2.0
a: 0.8
p_thresh: 0.20
start_frame: 2
num_frames: False
fps: 30.0
show: False
show_wait_time_ms: 200
